### ISSUE TITLE
"Something still holds a reference to a camera" error with multiple Blackfly S cameras

### ISSUE THREAD

**Issue by ebretl** [ros-drivers/flir_camera_driver#15] opened 2019-03-06 20:06 UTC
Setup:
- Ubuntu 16.04, ROS Kinetic
- Two FLIR Blackfly S cameras
- Spinnaker 1.13.0.31

Problem Description:
- On first launch, ROS driver works fine with one or two cameras
- After terminating the launch file with `Ctrl+C`, the first nodelet is able to unload, but the second one is not. The error encountered is:
```
[camera_nodelet_manager-1] killing on exit
terminate called after throwing an instance of 'Spinnaker::Exception'
  what():  Spinnaker: Can't clear a camera because something still holds a reference to the camera [-1004]
```
- On subsequent launches, the nodelet manager will crash and the error comes up again:
```
terminate called after throwing an instance of 'Spinnaker::Exception'
  what():  Spinnaker: Can't clear a camera because something still holds a reference to the camera [-1004]
================================================================================REQUIRED process [camera_nodelet_manager-1] has died!
```
- When launching only one camera, the error does not happen

**Comment by keenan-burnett** [comment] 2019-03-07 18:59
I've also seen this error come up in my current set up which is identical to ebretl.

@ebretl Would you mind sharing your launch file setup for running multiple blackfly S cameras at once? I've been struggling to get this working without throwing an error.

**Comment by ebretl** [comment] 2019-03-08 17:29
The launch file is here: https://github.com/AutoRally/autorally/blob/evan-flir-kinetic/autorally_core/launch/camera_flir.launch. This launch file is included for each camera (in cameras.launch), and both camera nodelets are loaded into the same manager. 

Also, try checking out my pull request and see if that fixes your issue. If not, we should work through it.

**Comment by keenan-burnett** [comment] 2019-03-08 18:35
Thanks for this. I was able to resolve my current issue with using multiple cameras after all. Although the issue I was seeing may be specific to my system. I have observed that the spinnaker camera driver will not allow two cameras to be running on the same PCIe card. I'll see if this issue crops up for me again, but it doesn't happen consistently.

**Comment by keenan-burnett** [comment] 2019-03-18 22:16
I haven't seen this error since I last commented.
I was able to resolve my own issues by setting usbcore.usbfs_memory_mb=10000 using the following instructions:
https://www.ptgrey.com/tan/10685

I incorrectly assumed that 1000 MB would be enough for two of my cameras.

**Comment by ghost** [comment] 2019-06-12 15:19
Thanks marking as duplicate of #12

**Closed as completed by ghost** 2019-06-12 15:19 UTC
